services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minimal-scraper
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
